name: ShellCheck

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install shellcheck

      - name: Run ShellCheck
        run: |
          shellcheck_output=$(shellcheck *.sh)
          echo "$shellcheck_output"
          if [ -n "$shellcheck_output" ]; then
            echo "ShellCheck found errors."
            exit 1
          fi
name: ShellCheck

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install shellcheck

      - name: Run ShellCheck
        run: shellcheck *.sh

